version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/esgwize
    file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
    #- location: scripts/rmoldsite.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    #- location: scripts/install_dependencies.sh
    - location: scripts/changeperms.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
