export const SET_COMPANY_NAMES = 'SET_COMPANY_NAMES';
export const SET_ACTIVE_STEP = 'SET_ACTIVE_STEP';
export const SET_TEMPLATE_DATA = 'SET_TEMPLATE_DATA';
export const SET_TEMPLATE_ACTIVE_STEP = 'SET_TEMPLATE_ACTIVE_STEP';
